add_newline = true
format = "[](fg:#313244)[λ ](fg:#a6e3a1 bg:#313244)$username[ ](fg:#313244 bg:#fab387)$directory[](fg:#fab387 bg:#a6e3a1)[$git_branch$git_status](bg:#a6e3a1)[](fg:#a6e3a1 bg:#89b4fa)$dotnet$elixir$elm$haskell$lua$nix_shell$nodejs$ocaml$python$rust$scala$shell$vagrant[](fg:#89b4fa bg:#cba6f7)$time[](fg:#cba6f7)$line_break$character"
palette = "catppuccin_mocha"

[character]
error_symbol = "[ ↳ ](fg:#f38ba8)"
success_symbol = "[ ↳ ](fg:#a6e3a1)"

[directory]
format = "[$path ]($style)"
style = "fg:#1e1e2e bg:#fab387"

[dotnet]
disabled = false
format = "[ $symbol($version)]($style)"
style = "fg:#1e1e2e bg:#89b4fa"
symbol = " "

[elixir]
disabled = false
format = "[ $symbol($version)]($style)"
style = "fg:#1e1e2e bg:#89b4fa"
symbol = " "

[elm]
disabled = false
format = "[ $symbol($version)]($style)"
style = "fg:#1e1e2e bg:#89b4fa"
symbol = " "

[git_branch]
format = "([ $symbol$branch]($style))"
style = "fg:#1e1e2e bg:#a6e3a1"
symbol = " "

[git_status]
disabled = false
format = "([ ❲$all_status$ahead_behind❳]($style))"
style = "bold\tfg:#1e1e2e bg:#a6e3a1"

[haskell]
disabled = false
format = "[ $symbol($version)]($style)"
style = "fg:#1e1e2e bg:#89b4fa"
symbol = " "

[lua]
disabled = false
format = "[ $symbol($version)]($style)"
style = "fg:#1e1e2e bg:#89b4fa"
symbol = " "

[nix_shell]
disabled = false
format = "[ $symbol($version)]($style)"
style = "fg:#1e1e2e bg:#89b4fa"
symbol = " "

[nodejs]
disabled = false
format = "[ $symbol($version)]($style)"
style = "fg:#1e1e2e bg:#89b4fa"
symbol = " "

[ocaml]
disabled = false
format = "[ $symbol($version)]($style)"
style = "fg:#1e1e2e bg:#89b4fa"
symbol = " "

[palettes.catppuccin_mocha]
base = "#1e1e2e"
blue = "#89b4fa"
crust = "#11111b"
flamingo = "#f2cdcd"
green = "#a6e3a1"
lavender = "#b4befe"
mantle = "#181825"
maroon = "#eba0ac"
mauve = "#cba6f7"
overlay0 = "#6c7086"
overlay1 = "#7f849c"
overlay2 = "#9399b2"
peach = "#fab387"
pink = "#f5c2e7"
red = "#f38ba8"
rosewater = "#f5e0dc"
sapphire = "#74c7ec"
sky = "#89dceb"
subtext0 = "#a6adc8"
subtext1 = "#bac2de"
surface0 = "#313244"
surface1 = "#45475a"
surface2 = "#585b70"
teal = "#94e2d5"
text = "#cdd6f4"
yellow = "#f9e2af"

[python]
disabled = false
format = "[ $symbol($version)]($style)"
style = "fg:#1e1e2e bg:#89b4fa"
symbol = " "

[rust]
disabled = false
format = "[ $symbol($version)]($style)"
style = "fg:#1e1e2e bg:#89b4fa"
symbol = " "

[scala]
disabled = false
format = "[ $symbol($version)]($style)"
style = "fg:#1e1e2e bg:#89b4fa"
symbol = " "

[time]
disabled = false
format = "[   $time]($style)"
style = "fg:#1e1e2e bg:#cba6f7"

[username]
format = "[$user ]($style)"
show_always = true
style_root = ""
style_user = "fg:#b4befe bg:#313244"

[vagrant]
disabled = false
format = "[ $symbol($version)]($style)"
style = "fg:#1e1e2e bg:#89b4fa"
symbol = " "
