fallback = '󰘔'

[icons]
kitty = ''
foot = ''
Alacritty = ''
firefox = ''
chromium = ''
nvim = ''
neovim = ''
code = '󰨞'
Code = '󰨞'
yazi = ''
btop = ''
htop = ''
pulsemixer = '󰕾'
pavucontrol = '󰕾'
mpv = ''
vlc = '󰕼'
spotify = ''
zathura = '󰈦'
discord = '󰙯'
slack = '󰒱'
thunderbird = ''
