complete -c set-accent -f
complete -c set-accent -a 'rosewater' -d '#f5e0dc'
complete -c set-accent -a 'flamingo'  -d '#f2cdcd'
complete -c set-accent -a 'pink'      -d '#f5c2e7'
complete -c set-accent -a 'mauve'     -d '#cba6f7 (default)'
complete -c set-accent -a 'red'       -d '#f38ba8'
complete -c set-accent -a 'maroon'    -d '#eba0ac'
complete -c set-accent -a 'peach'     -d '#fab387'
complete -c set-accent -a 'yellow'    -d '#f9e2af'
complete -c set-accent -a 'green'     -d '#a6e3a1'
complete -c set-accent -a 'teal'      -d '#94e2d5'
complete -c set-accent -a 'sky'       -d '#89dceb'
complete -c set-accent -a 'sapphire'  -d '#74c7ec'
complete -c set-accent -a 'blue'      -d '#89b4fa'
complete -c set-accent -a 'lavender'  -d '#b4befe'
