# Status Bar: waybar
#
# Read `man 5 sway-bar` for more information about this section.
# Read `man 5 waybar` for more information about the waybar instance style and layout configuration
#
# Requires: waybar

exec_always pkill waybar; waybar -c ~/.config/waybar/hosts/$(hostname).json
