default_border none
default_floating_border none
titlebar_border_thickness 0
titlebar_padding 0
for_window [class=".*"] border none
for_window [app_id=".*"] border none
for_window [app_id="float-mixer"] floating enable, resize set 900 500, move position center, move scratchpad
for_window [app_id="float-btop"] floating enable, resize set 1200 900, move position center, move scratchpad
for_window [app_id="float-notes"] floating enable, resize set 1000 700, move position center, move scratchpad
for_window [app_id="float-cheatsheet"] floating enable, resize set 960 640, move position center, move scratchpad
for_window [app_id="float-yazi"] floating enable, resize set 1200 800, move position center, move scratchpad
