return {
    "folke/which-key.nvim",
    event = "VeryLazy",
    opts = {
        -- your configuration comes here
        -- or leave it empty to use the default settings
        delay = 500,
        spec = {
            { "<leader>f", group = "Find (Telescope)" },
            { "<leader>ff", desc = "Find files" },
            { "<leader>fg", desc = "Find text (grep)" },
            { "<leader>fb", desc = "Find buffers" },
            { "<leader>fh", desc = "Find help" },
            { "<leader>fa", desc = "Find all files (ignore gitignore)" },
            { "<leader>fd", desc = "Find files in current directory" },

            { "<leader>l", group = "LSP" },
            { "<leader>lf", desc = "Format buffer" },
            { "<leader>lD", desc = "Go to declaration" },
            { "<leader>ld", desc = "Go to definition" },
            { "<leader>lh", desc = "Show hover" },
            { "<leader>li", desc = "Go to implementation" },
            { "<leader>ls", desc = "Show signature help" },
            { "<leader>lr", desc = "Show references" },
            { "<leader>lc", desc = "Rename symbol" },
            { "<leader>la", desc = "Code actions" },
            { "<leader>lj", desc = "Next diagnostic" },
            { "<leader>lk", desc = "Previous diagnostic" },

            { "<leader>c", group = "Copilot" },
            { "<leader>cc", desc = "CodeCompanion chat toggle" },
            { "<leader>ca", desc = "CodeCompanion action palette" },
            { "<leader>ci", desc = "CodeCompanion inline" },
            { "<leader>ce", desc = "CodeCompanion add to chat" },
            { "<leader>cm", desc = "Generate Rails migration" },
            { "<leader>cr", desc = "Rails best practices review" },
            { "<leader>ct", desc = "Generate Rails tests" },
            { "<leader>cf", desc = "Refactor Rails code" },
            { "<leader>cs", desc = "New CodeCompanion chat" },
            { "<leader>cl", desc = "Load CodeCompanion chat" },
            { "<leader>cw", desc = "Workspace context chat" },
            { "<leader>cp", desc = "Current file context chat" },
            { "<leader>cW", desc = "Advanced workspace analysis" },
            { "<leader>cM", desc = "Multi-file context builder" },
            { "<leader>cR", desc = "Rails workspace analysis" },
            { "<leader>cF", desc = "Pick related files for context" },
            { "<leader>cA", desc = "Auto-add Rails context files" },
            { "<leader>cX", desc = "Full workspace context analysis" },
            { "<leader>c@", desc = "VS Code-like @workspace query" },
            { "<leader>cT", desc = "Agent with file tools" },
            { "<leader>cN", desc = "File creation agent" },
            { "<leader>cA", desc = "Autonomous Rails agent" },
            { "<leader>cG", desc = "Toggle auto-tool mode" },
            { "<leader>cB", desc = "Build feature agent" },
            { "<leader>cD", desc = "Debug issue agent" },
            { "<leader>cR", desc = "Refactor current file" },
            { "<leader>cE", desc = "Edit selected code", mode = "v" },

            { "<leader>b", group = "Buffer" },
            { "<leader>bn", desc = "Next buffer" },
            { "<leader>bp", desc = "Previous buffer" },
            { "<leader>bd", desc = "Delete buffer" },

            { "<leader>w", group = "Window" },
            { "<leader>wv", desc = "Split vertically" },
            { "<leader>wh", desc = "Split horizontally" },
            { "<leader>we", desc = "Equalize splits" },
            { "<leader>wx", desc = "Close split" },

            { "<leader>a", group = "Tabs" },
            { "<leader>ao", desc = "Open new tab" },
            { "<leader>ax", desc = "Close tab" },
            { "<leader>an", desc = "Next tab" },
            { "<leader>ap", desc = "Previous tab" },

            { "<leader>r", group = "Rails/Ruby" },
            { "<leader>rv", desc = "Controller/View toggle" },
            { "<leader>rV", desc = "View Rails routes" },
            { "<leader>rS", desc = "View database schema" },
            { "<leader>rm", desc = "Go to model" },
            { "<leader>rg", desc = "Go to migration" },
            { "<leader>rt", desc = "Run Rake task" },
            { "<leader>rc", desc = "Rails console" },
            { "<leader>rs", desc = "Rails server" },
            { "<leader>rd", desc = "Debug nearest RSpec test" },
            { "<leader>rD", desc = "Debug RSpec file" },

            { "<leader>d", group = "Debug/Diagnostics" },
            { "<leader>db", desc = "Toggle breakpoint" },
            { "<leader>dB", desc = "Conditional breakpoint" },
            { "<leader>dc", desc = "Continue debugging" },
            { "<leader>ds", desc = "Step over" },
            { "<leader>di", desc = "Step into" },
            { "<leader>do", desc = "Step out" },
            { "<leader>dt", desc = "Terminate debugging" },
            { "<leader>du", desc = "Toggle debug UI" },
            { "<leader>dl", desc = "Run last debug session" },
            { "<leader>dr", desc = "Open debug REPL" },

            { "<leader>t", group = "Test" },
            { "<leader>tf", desc = "Test file" },
            { "<leader>tn", desc = "Test nearest" },
            { "<leader>ts", desc = "Test suite" },
            { "<leader>tl", desc = "Test last" },
            { "<leader>tv", desc = "Test output panel" },
            { "<leader>tS", desc = "Test summary" },
            { "<leader>to", desc = "Test output" },

            { "<leader>x", group = "Terminal" },
            { "<leader>xf", desc = "Float terminal" },
            { "<leader>xh", desc = "Horizontal terminal" },
            { "<leader>xv", desc = "Vertical terminal" },

            { "<leader>e", desc = "Open Oil (float)" },
            { "<leader>eh", desc = "Oil horizontal split" },
            { "<leader>ev", desc = "Oil vertical split" },
            { "-", desc = "Oil parent directory" },

            { "<leader>m", group = "Motion/Harpoon" },
            { "<leader>ma", desc = "Add to harpoon" },
            { "<leader>mh", desc = "Show harpoon menu" },
            { "<leader>md", desc = "Toggle Database UI" },
            { "<leader>1", desc = "Jump to harpoon 1" },
            { "<leader>2", desc = "Jump to harpoon 2" },
            { "<leader>3", desc = "Jump to harpoon 3" },
            { "<leader>4", desc = "Jump to harpoon 4" },

            { "<leader>u", group = "UI Toggles" },
            { "<leader>uh", desc = "Clear search highlights" },

            { "<leader>n", group = "Next (Treesitter)" },
            { "<leader>na", desc = "Swap parameter with next" },
            { "<leader>nf", desc = "Swap function with next" },

            { "<leader>p", group = "Previous (Treesitter)" },
            { "<leader>pa", desc = "Swap parameter with previous" },
            { "<leader>pf", desc = "Swap function with previous" },

            { "<leader>o", group = "Open/Toggle" },

            { "zR", desc = "Open all folds" },
            { "zM", desc = "Close all folds" },
            { "zr", desc = "Open folds except kinds" },
            { "zm", desc = "Close folds with" },
            { "zp", desc = "Peek fold or hover" },
            { "zO", desc = "Close other folds, open current" },
            { "[z", desc = "Previous fold" },
            { "]z", desc = "Next fold" },

            { "<leader>s", desc = "Sort selected lines", mode = "v" },
            { "<leader>de", desc = "Evaluate selection", mode = "v" },
            { "<leader>cf", desc = "Refactor Rails code", mode = "v" },
            { "<leader>cr", desc = "Rails best practices review", mode = "v" },
            { "<leader>ct", desc = "Generate Rails tests", mode = "v" },
        },
    },
    keys = {
        {
            "<leader>?",
            function()
                require("which-key").show({ global = false })
            end,
            desc = "Buffer Local Keymaps (which-key)",
        },
    },
}
